#!/bin/sh

MYDIR=$(dirname "$(readlink -f "$0")")
TOPDIR="$MYDIR/.."

export LD_LIBRARY_PATH="$TOPDIR/lib/cpgf/lib:$TOPDIR/build/src/core:$TOPDIR/build/src/widgets:$TOPDIR/build/src/qml:$TOPDIR/build/src/gui"

echo "running specs.."
"$TOPDIR/build/tests/spec/spec"  --output=color || exit 1

echo ""
echo "running features"
"$TOPDIR/build/tests/features/features"


